const APP_VERSION="1.4.1", API="https://api.openligadb.de", LEAGUE="bl1", SEASON=2026;
let currentGroup=1, teams=[],leagueTable=[],notificationTimer=null,liveTimer=null,countdownTimer=null,currentMatches=[],previousScores=new Map(),changedMatches=new Set();
const $=s=>document.querySelector(s);

function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function finalScore(m){const results=(m.matchResults||[]).filter(x=>x.resultTypeID===2||x.resultName==="Endergebnis");const r=results.at(-1)||(m.matchResults||[]).at(-1);return r?`${r.pointsTeam1}:${r.pointsTeam2}`:"–"}
function finalResult(m){const results=(m.matchResults||[]).filter(x=>x.resultTypeID===2||x.resultName==="Endergebnis");return results.at(-1)||(m.matchResults||[]).at(-1)}
function dateText(s){return s?new Intl.DateTimeFormat("de-DE",{weekday:"short",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(s)):""}
function calendarDate(d){return new Date(d).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"")}
function calendarEscape(s=""){return String(s).replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function calendarEvent(m){const start=new Date(m.matchDateTime),end=new Date(start.getTime()+2*60*60*1000),home=m.team1?.teamName||"Heimteam",away=m.team2?.teamName||"Auswärtsteam",venue=[m.location?.locationStadium,m.location?.locationCity].filter(Boolean).join(", ");return ["BEGIN:VEVENT",`UID:ligakompakt-${m.matchID||start.getTime()}@andreas-binder`,`DTSTAMP:${calendarDate(new Date())}`,`DTSTART:${calendarDate(start)}`,`DTEND:${calendarDate(end)}`,`SUMMARY:${calendarEscape(`${home} – ${away}`)}`,`DESCRIPTION:${calendarEscape("Bundesliga-Spiel · gespeichert mit LigaKompakt")}`,`LOCATION:${calendarEscape(venue)}`,"END:VEVENT"]}
async function deliverCalendarFile(events,name,title){const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//LigaKompakt//DE","CALSCALE:GREGORIAN","METHOD:PUBLISH",...events.flatMap(calendarEvent),"END:VCALENDAR"].join("\r\n"),file=new File([ics],name,{type:"text/calendar"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title,files:[file]});return}const url=URL.createObjectURL(file),a=document.createElement("a");a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function saveMatchToCalendar(m){
  const home=m.team1?.teamName||"Heimteam",away=m.team2?.teamName||"Auswärtsteam";await deliverCalendarFile([m],`LigaKompakt-${home}-${away}.ics`,`${home} – ${away}`)
}
function subscribeTeamCalendar(teamId){const calendarUrl=`https://catbinderson.github.io/Bundesliga-Kompakt/calendars/${encodeURIComponent(teamId)}.ics`;if(/Android/i.test(navigator.userAgent)){location.href=`https://calendar.google.com/calendar/render?cid=${encodeURIComponent(calendarUrl)}`;return}location.href=calendarUrl.replace(/^https:/,"webcal:")}
async function shareMatch(m){
  const home=m.team1?.teamName||"Heimteam",away=m.team2?.teamName||"Auswärtsteam",title=`${home} – ${away}`,detail=m.matchIsFinished?`Endstand: ${finalScore(m)}`:`Anstoß: ${dateText(m.matchDateTime)}`,text=`⚽ ${title}\n${detail}\nLigaKompakt`,url=new URL("./",location.href).href;
  if(navigator.share){await navigator.share({title,text,url});return}
  await navigator.clipboard.writeText(`${text}\n${url}`);const status=$("#liveDot"),old=status.textContent;status.textContent="Link kopiert";setTimeout(()=>status.textContent=old,1800)
}
function isLiveMatch(m){const kickoff=new Date(m.matchDateTime),now=new Date();return!m.matchIsFinished&&now>=kickoff&&(now-kickoff)<3*60*60*1000}
function countdownText(target){const seconds=Math.max(0,Math.floor((target-Date.now())/1000)),d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),min=Math.floor(seconds%3600/60),s=seconds%60;return d?`${d} T ${h} Std ${min} Min`:h?`${h} Std ${min} Min ${s} Sek`:`${min} Min ${s} Sek`}
function updateCountdown(){const el=$("#nextKickoff"),target=Number(el?.dataset.target);if(!el||!target)return;const strong=el.querySelector("strong");if(target<=Date.now()){strong.textContent="Anpfiff läuft";return}strong.textContent=countdownText(target)}
function renderLiveCenter(matches){const live=matches.filter(isLiveMatch),finished=matches.filter(m=>m.matchIsFinished),upcoming=matches.filter(m=>!m.matchIsFinished&&!isLiveMatch(m)&&new Date(m.matchDateTime)>new Date()).sort((a,b)=>new Date(a.matchDateTime)-new Date(b.matchDateTime));$("#liveCount").textContent=live.length;$("#finishedCount").textContent=finished.length;$("#upcomingCount").textContent=upcoming.length;const next=$("#nextKickoff");if(live.length){next.removeAttribute("data-target");next.querySelector("span").textContent="Gerade live";next.querySelector("strong").textContent=live.map(m=>`${m.team1?.shortName||m.team1?.teamName} – ${m.team2?.shortName||m.team2?.teamName}`).join(" · ")}else if(upcoming.length){const m=upcoming[0],target=new Date(m.matchDateTime).getTime();next.dataset.target=String(target);next.querySelector("span").textContent=`Nächster Anpfiff · ${m.team1?.shortName||m.team1?.teamName} – ${m.team2?.shortName||m.team2?.teamName}`;updateCountdown()}else{next.removeAttribute("data-target");next.querySelector("span").textContent="Spieltag";next.querySelector("strong").textContent="Alle Spiele beendet"}}
function skeletons(el,count=3){el.innerHTML=Array.from({length:count},()=>'<div class="card skeleton"><i></i><i></i><i></i></div>').join("")}
async function get(path){const r=await fetch(API+path,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function clubColors(name=""){const n=name.toLowerCase(),sets=[["dortmund","#fdeb19","#111111"],["bremen","#00864a","#ffffff"],["wolfsburg","#65b32e","#ffffff"],["gladbach","#15a05c","#111111"],["augsburg","#ba3733","#46714b"],["st. pauli","#6f4e37","#ffffff"],["hamburg","#005aaa","#ffffff"],["hoffenheim","#1961a9","#ffffff"],["heidenheim","#e30613","#184b91"],["freiburg","#e30613","#111111"],["mainz","#c3142d","#ffffff"],["frankfurt","#e1000f","#111111"],["leverkusen","#e32221","#111111"],["leipzig","#dd0741","#ffffff"],["stuttgart","#e32219","#ffffff"],["bayern","#dc052d","#0066b2"],["union","#e30613","#ffffff"],["köln","#ed1c24","#ffffff"]];return sets.find(([key])=>n.includes(key))?.slice(1)||["#39db86","#4fa3ff"]}
function formFor(matches,teamId){return matches.filter(m=>m.matchIsFinished).sort((a,b)=>new Date(b.matchDateTime)-new Date(a.matchDateTime)).slice(0,5).reverse().map(m=>{const r=finalResult(m);if(!r)return"–";const home=String(m.team1?.teamId)===String(teamId),own=home?r.pointsTeam1:r.pointsTeam2,other=home?r.pointsTeam2:r.pointsTeam1;return own>other?"S":own<other?"N":"U"})}
function standingId(t){return String(t?.teamInfoId??t?.teamId??"")}
function formBadges(form){return form.length?form.map(x=>`<span class="form-${x}">${x}</span>`).join(""):'<small>Noch keine Spiele</small>'}
function setupComparison(){if(!teams.length||!leagueTable.length)return;const a=$("#compareTeamA"),b=$("#compareTeamB"),oldA=a.value,oldB=b.value,options=teams.map(t=>`<option value="${t.teamId}">${escapeHtml(t.teamName)}</option>`).join("");a.innerHTML=options;b.innerHTML=options;const favorite=localStorage.getItem("ligakompakt.favorite"),first=favorite&&teams.some(t=>String(t.teamId)===favorite)?favorite:String(teams[0]?.teamId||""),second=String(teams.find(t=>String(t.teamId)!==first)?.teamId||"");a.value=oldA&&teams.some(t=>String(t.teamId)===oldA)?oldA:first;b.value=oldB&&teams.some(t=>String(t.teamId)===oldB)?oldB:second;if(a.value&&b.value)renderComparison().catch(console.warn)}
function compareMetric(label,a,b,higher=true,suffix=""){const av=Number(a??0),bv=Number(b??0),aBest=higher?av>bv:av<bv,bBest=higher?bv>av:bv<av;return `<div class="compare-metric"><strong class="${aBest?"better":""}">${a??"–"}${suffix}</strong><span>${label}</span><strong class="${bBest?"better":""}">${b??"–"}${suffix}</strong></div>`}
function headToHeadStats(matches,idA){let winsA=0,winsB=0,draws=0,goalsA=0,goalsB=0;const finished=matches.filter(m=>m.matchIsFinished&&finalResult(m));for(const m of finished){const r=finalResult(m),aHome=String(m.team1?.teamId)===idA,aGoals=aHome?r.pointsTeam1:r.pointsTeam2,bGoals=aHome?r.pointsTeam2:r.pointsTeam1;goalsA+=aGoals;goalsB+=bGoals;if(aGoals>bGoals)winsA++;else if(aGoals<bGoals)winsB++;else draws++}return{finished,winsA,winsB,draws,goalsA,goalsB}}
function duelRows(matches){return matches.sort((a,b)=>new Date(b.matchDateTime)-new Date(a.matchDateTime)).slice(0,5).map(m=>`<div class="duel-row"><span>${new Intl.DateTimeFormat("de-DE",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(m.matchDateTime))}</span><strong>${escapeHtml(m.team1?.shortName||m.team1?.teamName||"")} <b>${finalScore(m)}</b> ${escapeHtml(m.team2?.shortName||m.team2?.teamName||"")}</strong><small>${escapeHtml(m.leagueName||"")}</small></div>`).join("")}
async function renderComparison(){const idA=$("#compareTeamA").value,idB=$("#compareTeamB").value,result=$("#comparisonResult");if(!idA||!idB)return;if(idA===idB){result.innerHTML='<div class="error compare-error">Bitte zwei unterschiedliche Vereine auswählen.</div>';return}result.innerHTML='<div class="card skeleton"><i></i><i></i><i></i></div>';const teamA=teams.find(t=>String(t.teamId)===idA),teamB=teams.find(t=>String(t.teamId)===idB),standingA=leagueTable.find(t=>standingId(t)===idA),standingB=leagueTable.find(t=>standingId(t)===idB),[matchesA,matchesB,duels]=await Promise.all([get(`/getmatchesbyteamid/${idA}/5/0`),get(`/getmatchesbyteamid/${idB}/5/0`),get(`/getmatchdata/${idA}/${idB}`)]),formA=formFor(matchesA,idA),formB=formFor(matchesB,idB),placeA=standingA?leagueTable.indexOf(standingA)+1:"–",placeB=standingB?leagueTable.indexOf(standingB)+1:"–",h2h=headToHeadStats(duels,idA),nameA=teamA?.shortName||teamA?.teamName||"Verein 1",nameB=teamB?.shortName||teamB?.teamName||"Verein 2";result.innerHTML=`<div class="card comparison-card"><div class="compare-teams"><div><img src="${escapeHtml(teamA?.teamIconUrl||"")}" alt=""><strong>${escapeHtml(nameA)}</strong><div class="form-row">${formBadges(formA)}</div></div><span>VS</span><div><img src="${escapeHtml(teamB?.teamIconUrl||"")}" alt=""><strong>${escapeHtml(nameB)}</strong><div class="form-row">${formBadges(formB)}</div></div></div><div class="compare-metrics">${compareMetric("Tabellenplatz",placeA,placeB,false)}${compareMetric("Punkte",standingA?.points,standingB?.points)}${compareMetric("Tordifferenz",standingA?.goalDiff,standingB?.goalDiff)}${compareMetric("Siege",standingA?.won,standingB?.won)}</div><div class="h2h"><div class="h2h-head"><div><div class="eyebrow">BEGEGNUNGSSTATISTIK</div><h3>${h2h.finished.length} direkte Duelle</h3></div><span>Torverhältnis ${h2h.goalsA}:${h2h.goalsB}</span></div><div class="h2h-score"><div><strong>${h2h.winsA}</strong><span>Siege ${escapeHtml(nameA)}</span></div><div><strong>${h2h.draws}</strong><span>Unentschieden</span></div><div><strong>${h2h.winsB}</strong><span>Siege ${escapeHtml(nameB)}</span></div></div><div class="duel-list"><div class="eyebrow">LETZTE BEGEGNUNGEN</div>${h2h.finished.length?duelRows(h2h.finished):'<p class="muted">Keine früheren Begegnungen vorhanden.</p>'}</div></div></div>`}
function notificationsSupported(){return"Notification"in window&&"serviceWorker"in navigator}
async function sendNotification(title,body){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:"icon.svg",badge:"icon.svg",tag:"ligakompakt-match",renotify:true,data:{url:"./"}})}
function updateNotificationUI(){const supported=notificationsSupported(),enabled=supported&&localStorage.getItem("ligakompakt.notifications")==="1"&&Notification.permission==="granted",toggle=$("#notificationToggle"),test=$("#notificationTest"),status=$("#notificationStatus");if(!toggle)return;toggle.disabled=!supported;test.disabled=!enabled;toggle.textContent=enabled?"Ausschalten":"Einschalten";status.textContent=!supported?"Auf diesem Gerät nicht verfügbar.":Notification.permission==="denied"?"In den iPhone-Einstellungen blockiert.":enabled?"Aktiv, solange LigaKompakt geöffnet oder aktiv ist.":"Benachrichtigungen sind ausgeschaltet."}
async function enableNotifications(){if(!notificationsSupported())return;const enabled=localStorage.getItem("ligakompakt.notifications")==="1";if(enabled){localStorage.removeItem("ligakompakt.notifications");clearInterval(notificationTimer);notificationTimer=null;updateNotificationUI();return}const permission=await Notification.requestPermission();if(permission==="granted"){localStorage.setItem("ligakompakt.notifications","1");await sendNotification("LigaKompakt Spielalarm","Benachrichtigungen sind jetzt eingeschaltet.");startNotificationMonitor()}updateNotificationUI()}
async function checkFavoriteUpdates(){if(localStorage.getItem("ligakompakt.notifications")!=="1"||Notification.permission!=="granted")return;const teamId=localStorage.getItem("ligakompakt.favorite");if(!teamId)return;try{const matches=await get(`/getmatchesbyteamid/${teamId}/1/1`),saved=JSON.parse(localStorage.getItem("ligakompakt.matchState")||"{}"),next={...saved};for(const m of matches){const key=String(m.matchID),score=finalScore(m),started=Date.now()>=new Date(m.matchDateTime).getTime(),previous=saved[key],pair=`${m.team1?.shortName||m.team1?.teamName} – ${m.team2?.shortName||m.team2?.teamName}`;if(previous){if(score!=="–"&&score!==previous.score)await sendNotification(`⚽ Tor · ${score}`,pair);else if(m.matchIsFinished&&!previous.finished)await sendNotification(`Abpfiff · ${score}`,pair);else if(started&&!previous.started&&!m.matchIsFinished)await sendNotification("Anpfiff",pair)}next[key]={score,started,finished:!!m.matchIsFinished}}localStorage.setItem("ligakompakt.matchState",JSON.stringify(next))}catch(e){console.warn("Spielalarm:",e)}}
function startNotificationMonitor(){clearInterval(notificationTimer);if(localStorage.getItem("ligakompakt.notifications")==="1"&&Notification.permission==="granted"){checkFavoriteUpdates();notificationTimer=setInterval(checkFavoriteUpdates,60000)}updateNotificationUI()}
async function checkForAppUpdate(){
  try{const r=await fetch(`version.json?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)return;const data=await r.json();if(data.version&&data.version!==APP_VERSION){$("#liveDot").textContent="Update …";const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith("ligakompakt-")).map(k=>caches.delete(k)));const reg=await navigator.serviceWorker.getRegistration();await reg?.update();if(reg?.waiting)reg.waiting.postMessage({type:"SKIP_WAITING"});setTimeout(()=>location.replace(`./?v=${encodeURIComponent(data.version)}&t=${Date.now()}`),500)}}catch(e){console.warn("Versionsprüfung:",e)}
}
function matchDetails(m){
  const half=(m.matchResults||[]).find(r=>r.resultTypeID===1||/halbzeit/i.test(r.resultName||"")),venue=[m.location?.locationStadium,m.location?.locationCity].filter(Boolean).join(" · "),goals=(m.goals||[]).slice().sort((a,b)=>(a.matchMinute||0)-(b.matchMinute||0));
  const rows=[];
  if(venue)rows.push(`<div class="detail-line"><span>⌖</span><div><small>SPIELORT</small><strong>${escapeHtml(venue)}</strong></div></div>`);
  if(half)rows.push(`<div class="detail-line"><span>◐</span><div><small>HALBZEIT</small><strong>${half.pointsTeam1}:${half.pointsTeam2}</strong></div></div>`);
  if(goals.length)rows.push(`<div class="goal-list"><small>TORE</small>${goals.map(g=>`<div><b>${g.scoreTeam1}:${g.scoreTeam2}</b><span>${escapeHtml(g.goalGetterName||"Torschütze unbekannt")}${g.matchMinute?` · ${g.matchMinute}. Min.`:""}${g.isPenalty?" · Elfmeter":""}${g.isOwnGoal?" · Eigentor":""}</span></div>`).join("")}</div>`);
  if(!rows.length)rows.push('<p class="muted">Weitere Spieldetails sind noch nicht verfügbar.</p>');
  const calendar=!m.matchIsFinished&&new Date(m.matchDateTime)>new Date()?'<button type="button" class="calendar-btn"><span>＋</span> Termin</button>':"";
  return `<div class="match-details"><div class="detail-inner">${rows.join("")}</div></div><div class="match-actions">${calendar}<button type="button" class="share-btn"><span>↗</span> Teilen</button><button type="button" class="details-toggle" aria-expanded="false"><span>Details</span><b>⌄</b></button></div>`;
}

function matchCard(m){
  const node=$("#matchTpl").content.firstElementChild.cloneNode(true), kickoff=new Date(m.matchDateTime), now=new Date();node.dataset.matchId=String(m.matchID||"");
  node.querySelector(".match-meta").textContent=`${m.group?.groupName||""} · ${dateText(m.matchDateTime)}`;
  node.querySelector(".home img").src=m.team1?.teamIconUrl||""; node.querySelector(".home span").textContent=m.team1?.shortName||m.team1?.teamName||"";
  node.querySelector(".away img").src=m.team2?.teamIconUrl||""; node.querySelector(".away span").textContent=m.team2?.shortName||m.team2?.teamName||"";
  const state=node.querySelector(".match-state"), isLive=isLiveMatch(m);
  if(m.matchIsFinished){node.querySelector(".score").textContent=finalScore(m);node.querySelector(".kickoff").textContent="Endstand";state.textContent="BEENDET";state.classList.add("done")}
  else if(isLive){const minute=Math.max(1,Math.min(90,Math.floor((now-kickoff)/60000)+1));node.querySelector(".score").textContent=finalScore(m)==="–"?"LIVE":finalScore(m);node.querySelector(".kickoff").textContent=`ca. ${minute}. Minute`;state.textContent=`LIVE · ${minute}'`;state.classList.add("live")}
  else{node.querySelector(".score").textContent=new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(kickoff);node.querySelector(".kickoff").textContent=new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit"}).format(kickoff);state.textContent="ANSTEHEND"}
  if(changedMatches.has(String(m.matchID)))node.classList.add("score-changed");node.insertAdjacentHTML("beforeend",matchDetails(m));const button=node.querySelector(".details-toggle"),calendar=node.querySelector(".calendar-btn"),share=node.querySelector(".share-btn");
  button.addEventListener("click",e=>{e.stopPropagation();const open=node.classList.toggle("details-open");button.setAttribute("aria-expanded",String(open));button.querySelector("span").textContent=open?"Spieldetails schließen":"Spieldetails öffnen"});
  if(calendar)calendar.addEventListener("click",e=>{e.stopPropagation();saveMatchToCalendar(m).catch(error=>{if(error?.name!=="AbortError")showError(error)})});
  share.addEventListener("click",e=>{e.stopPropagation();shareMatch(m).catch(error=>{if(error?.name!=="AbortError")showError(error)})});
  return node;
}
function renderMatches(el,matches){el.innerHTML="";if(!matches.length){el.innerHTML='<div class="card muted">Keine Spiele gefunden.</div>';return}matches.forEach(m=>el.appendChild(matchCard(m)))}
function renderFavoriteHero(teamId){const wrap=$("#favoriteHero"),t=teams.find(x=>String(x.teamId)===String(teamId));if(!t){wrap.innerHTML="";return}wrap.innerHTML=`<button class="favorite-strip" data-goto="club"><img src="${escapeHtml(t.teamIconUrl||"")}" alt=""><span><span class="eyebrow">MEIN VEREIN</span><strong>${escapeHtml(t.teamName)}</strong><small>Spiele & Übersicht öffnen</small></span><span class="fav-pill">★ FAVORIT</span></button>`;wrap.firstElementChild.onclick=()=>showView("club")}
async function loadTable(){const data=await get(`/getbltable/${LEAGUE}/${SEASON}`);leagueTable=data;$("#tableBody").innerHTML=data.map((t,i)=>`<tr><td>${i+1}</td><td><div class="club-row"><img src="${escapeHtml(t.teamIconUrl||"")}" alt=""><span>${escapeHtml(t.shortName||t.teamName)}</span></div></td><td>${t.matches}</td><td class="wide-col">${t.won}</td><td class="wide-col">${t.draw}</td><td class="wide-col">${t.lost}</td><td>${t.goalDiff>=0?"+":""}${t.goalDiff}</td><td><b>${t.points}</b></td></tr>`).join("");setupComparison()}
async function loadFixtures(group=currentGroup){skeletons($("#fixturesList"));const data=await get(`/getmatchdata/${LEAGUE}/${SEASON}/${group}`);$("#matchdayTitle").textContent=`${group}. Spieltag`;renderMatches($("#fixturesList"),data)}
async function loadToday(silent=false){if(!silent)skeletons($("#todayMatches"));const data=await get(`/getmatchdata/${LEAGUE}`);changedMatches=new Set();data.forEach(m=>{const key=String(m.matchID),score=finalScore(m),old=previousScores.get(key);if(old&&score!=="–"&&old!==score)changedMatches.add(key);previousScores.set(key,score)});currentMatches=data;currentGroup=data[0]?.group?.groupOrderID||1;$("#todayTitle").textContent=`${currentGroup}. Spieltag`;$("#todaySub").textContent=`Live-Daten · aktualisiert ${new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date())}`;renderLiveCenter(data);renderMatches($("#todayMatches"),data);if(changedMatches.size)setTimeout(()=>document.querySelectorAll(".score-changed").forEach(x=>x.classList.remove("score-changed")),2500)}
function startLiveCenter(){clearInterval(liveTimer);clearInterval(countdownTimer);liveTimer=setInterval(()=>{if(document.visibilityState==="visible"&&navigator.onLine)loadToday(true).catch(console.warn)},30000);countdownTimer=setInterval(updateCountdown,1000)}
async function loadTeams(){teams=await get(`/getavailableteams/${LEAGUE}/${SEASON}`);const options='<option value="">Verein wählen …</option>'+teams.map(t=>`<option value="${t.teamId}">${escapeHtml(t.teamName)}</option>`).join("");$("#teamSelect").innerHTML=options;$("#onboardingTeam").innerHTML=options;setupComparison();const saved=localStorage.getItem("ligakompakt.favorite");if(saved){$("#teamSelect").value=saved;$("#onboardingTeam").value=saved;renderFavoriteHero(saved);await loadClub(saved,false)}else if(localStorage.getItem("ligakompakt.onboarded")!=="1")$("#onboarding").classList.remove("hidden")}
async function loadClub(teamId,save=true){
  if(!teamId){$("#clubHeader").innerHTML="";$("#clubContent").innerHTML="";renderFavoriteHero("");return}
  if(save){localStorage.setItem("ligakompakt.favorite",teamId);localStorage.setItem("ligakompakt.onboarded","1");localStorage.removeItem("ligakompakt.matchState")}
  $("#teamSelect").value=teamId;$("#onboardingTeam").value=teamId;renderFavoriteHero(teamId);
  const team=teams.find(t=>String(t.teamId)===String(teamId)),[primary,secondary]=clubColors(team?.teamName),style=`--club-primary:${primary};--club-secondary:${secondary}`;
  $("#clubHeader").innerHTML='<div class="card club-dashboard skeleton"><i></i><i></i><i></i></div>';
  $("#clubContent").innerHTML='<div class="section-head compact"><h3>Spiele werden geladen …</h3></div>';
  const [matches,table]=await Promise.all([get(`/getmatchesbyteamid/${teamId}/5/3`),get(`/getbltable/${LEAGUE}/${SEASON}`)]),now=new Date();
  const upcoming=matches.filter(m=>!m.matchIsFinished&&new Date(m.matchDateTime)>=now).sort((a,b)=>new Date(a.matchDateTime)-new Date(b.matchDateTime)).slice(0,3);
  const past=matches.filter(m=>m.matchIsFinished).sort((a,b)=>new Date(b.matchDateTime)-new Date(a.matchDateTime)).slice(0,3),standing=table.find(t=>String(t.teamInfoId)===String(teamId)||String(t.teamId)===String(teamId)),position=Math.max(1,table.indexOf(standing)+1),form=formFor(matches,teamId);
  $("#clubHeader").innerHTML=`<div class="card club-dashboard" style="${style}"><div class="club-identity"><img src="${escapeHtml(team?.teamIconUrl||"")}" alt=""><div><div class="eyebrow">MEIN VEREIN</div><h2>${escapeHtml(team?.teamName||"")}</h2><div class="form-row" aria-label="Form der letzten Spiele">${form.length?form.map(x=>`<span class="form-${x}">${x}</span>`).join(""):'<small>Noch keine Ergebnisse</small>'}</div></div></div><div class="club-stats"><div><strong>${standing?position:"–"}</strong><span>Platz</span></div><div><strong>${standing?.points??"–"}</strong><span>Punkte</span></div><div><strong>${standing?(standing.goalDiff>=0?"+":"")+standing.goalDiff:"–"}</strong><span>Tordifferenz</span></div></div></div>`;
  $("#clubContent").innerHTML='<button id="subscribeCalendar" class="season-calendar-btn"><span>＋</span><span><strong>Kalender abonnieren</strong><small>Alle Spiele automatisch im Kalender</small></span></button><div class="section-head compact"><div><div class="eyebrow">AUSBLICK</div><h3>Nächstes Spiel</h3></div></div><div id="clubNext" class="stack next-match"></div><div class="section-head compact"><div><div class="eyebrow">WEITERE TERMINE</div><h3>Danach</h3></div></div><div id="clubUpcoming" class="stack"></div><div class="section-head compact"><div><div class="eyebrow">RÜCKBLICK</div><h3>Letzte Ergebnisse</h3></div></div><div id="clubPast" class="stack"></div>';
  $("#subscribeCalendar").onclick=()=>subscribeTeamCalendar(teamId);
  renderMatches($("#clubNext"),upcoming.slice(0,1));
  renderMatches($("#clubUpcoming"),upcoming.slice(1));renderMatches($("#clubPast"),past);startNotificationMonitor();
}
function setupMatchdays(){const s=$("#matchdaySelect");s.innerHTML=Array.from({length:34},(_,i)=>`<option value="${i+1}">${i+1}. Spieltag</option>`).join("");s.value=String(currentGroup);s.onchange=e=>loadFixtures(Number(e.target.value)).catch(showError)}
function showError(e){console.error(e);$("#todayMatches").innerHTML='<div class="error">Daten konnten nicht geladen werden. Bitte später erneut versuchen.</div>';$("#liveDot").textContent=navigator.onLine?"Fehler":"Offline"}
function showView(id){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===id));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===id));window.scrollTo({top:0,behavior:"smooth"})}
function updateNetwork(){const offline=!navigator.onLine;$("#networkBanner").classList.toggle("hidden",!offline);if(offline)$("#liveDot").textContent="Offline"}
async function refreshAll(){try{$("#refreshBtn").classList.add("spinning");$("#liveDot").textContent="Lädt …";await Promise.all([loadToday(),loadTable(),loadTeams()]);setupMatchdays();$("#matchdaySelect").value=String(currentGroup);await loadFixtures(currentGroup);$("#liveDot").textContent=navigator.onLine?"Online":"Offline";$("#updatedAt").textContent=`Zuletzt aktualisiert: ${new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date())}`}catch(e){showError(e)}finally{$("#refreshBtn").classList.remove("spinning")}}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll("[data-goto]").forEach(b=>b.onclick=()=>showView(b.dataset.goto));
$("#teamSelect").onchange=e=>loadClub(e.target.value).catch(showError);$("#refreshBtn").onclick=refreshAll;
$("#notificationToggle").onclick=()=>enableNotifications().catch(showError);$("#notificationTest").onclick=()=>sendNotification("LigaKompakt Test","Der Spielalarm funktioniert auf diesem Gerät.").catch(showError);
$("#compareBtn").onclick=()=>renderComparison().catch(showError);$("#compareTeamA").onchange=()=>renderComparison().catch(showError);$("#compareTeamB").onchange=()=>renderComparison().catch(showError);
$("#saveFavorite").onclick=async()=>{const id=$("#onboardingTeam").value;if(!id)return;await loadClub(id);$("#onboarding").classList.add("hidden")};$("#skipFavorite").onclick=()=>{localStorage.setItem("ligakompakt.onboarded","1");$("#onboarding").classList.add("hidden")};
addEventListener("online",()=>{updateNetwork();refreshAll();checkForAppUpdate()});addEventListener("offline",updateNetwork);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){checkForAppUpdate();loadToday(true).catch(console.warn)}});updateNetwork();updateNotificationUI();startLiveCenter();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js",{updateViaCache:"none"}).then(reg=>{reg.update();startNotificationMonitor()});checkForAppUpdate();setInterval(checkForAppUpdate,5*60*1000);refreshAll();
