const BUILD=2,CACHE="ligakompakt-v1.0.0-build2",ASSETS=["./","index.html","info.html","einladen.html","teilen.html","statistik.html","admin.html","styles.css?v=1.0.0-fix1","app.js?v=1.0.0","tips-persistence.js?v=1","share-fix.js?v=2","h2h-per-match.js?v=1","update-manager.js?v=2","manifest.webmanifest","icon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","apple-touch-icon.png","qr-ligakompakt.png","social-preview.jpg","facebook-preview-v5.jpg","version.json"];
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener("activate",e=>e.waitUntil((async()=>{await Promise.all((await caches.keys()).filter(k=>k.startsWith("ligakompakt-")&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});
async function injectUpdateManager(response){if(!response)return response;const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;let html=await response.text();if(!html.includes("update-manager.js")){const tag=`<script src="update-manager.js?v=${BUILD}"></script>`;html=html.includes("</body>")?html.replace("</body>",`${tag}\n</body>`):html+tag}const headers=new Headers(response.headers);headers.set("cache-control","no-cache");headers.delete("content-length");return new Response(html,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener("fetch",e=>{
  if(e.request.method!=="GET")return;const url=new URL(e.request.url),api=url.hostname==="api.openligadb.de";
  if(api){e.respondWith(fetch(e.request,{cache:"no-store"}).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}).catch(()=>caches.match(e.request)));return}
  if(url.origin!==self.location.origin)return;
  if(url.pathname.endsWith("version.json")||url.pathname.endsWith("sw.js")||url.pathname.endsWith("update-manager.js")){e.respondWith(fetch(e.request,{cache:"no-store"}));return}
  if(e.request.mode==="navigate"){e.respondWith((async()=>{try{const r=await fetch(e.request,{cache:"reload"});const copy=r.clone();caches.open(CACHE).then(c=>c.put("index.html",copy)).catch(()=>{});return await injectUpdateManager(r)}catch{const cached=await caches.match(e.request)||await caches.match("index.html");return cached?await injectUpdateManager(cached):Response.error()}})());return}
  e.respondWith(fetch(e.request,{cache:"reload"}).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}).catch(async()=>await caches.match(e.request)||await caches.match("index.html")));
});
self.addEventListener("notificationclick",e=>{e.notification.close();e.waitUntil(clients.matchAll({type:"window",includeUncontrolled:true}).then(list=>list[0]?list[0].focus():clients.openWindow(e.notification.data?.url||"./")))});
